"""create source registry tables

Revision ID: fd6be8e34b7b
Revises: 
Create Date: 2026-05-27 18:25:08.486177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6be8e34b7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tax_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('tax_type_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('authority_level', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('short_title', sa.String(length=255), nullable=True),
    sa.Column('issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('official_reference', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_retrieval_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=100), nullable=False),
    sa.Column('retrieval_source', sa.Text(), nullable=True),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieval_status', sa.String(length=50), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('operator_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('enforcement_date', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version_status', sa.String(length=50), nullable=False),
    sa.Column('supersedes_version_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['source_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_versions')
    op.drop_table('source_retrieval_log')
    op.drop_table('source_documents')
    op.drop_table('tax_types')
    op.drop_table('countries')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
